### ISSUE TITLE
Support for header families 

### ISSUE THREAD

**Issue by wookievx** [pheymann/typedapi#28]
Very recently i came across a certain limitation of typed-api, as title suggests it is about header families, for example all headers starting with l5d-ctx (linkerd context).  Program may not be interested to use all of the headers of that family but it might be required to forward those when doing request to some other service. Unfortunately it is impossible to do this given the current API, but i think it should be pretty simple to add something like the following:
```scala
  val MyApi = "header" :> "family" :> Header[String].family("my-hdr-family") :> Get[Json, A]
```
Given the following definition one can interpret it as to extract all headers starting with `my-hdr-family` on the server-side, and to provide zero or more headers on the client side.

**Comment by wookievx** [comment]
I am also not sure whether headers with dashes in names are supported at all (one have to use symbol syntax to define their names, while scala does not support dash inside symbol definition)

**Comment by pheymann** [comment]
Hi @wookievx ,
thanks for using typedapi. Regarding your issue. Unfortunately, I don't understand what you try to explain. I have never heard of header families and googling for it didn't bring a meaningful result. Could you maybe give me a bit more context? Maybe an example which shows what the client sends and the server reads.

Furthermore, I am currently preparing 0.1.0 in the 0.1.0-release branch (release end of this week 🤞 ). There I added new features for headers. You can now add static headers in the API `:> Header("Accept", "*")` which will send this header on every request/response but you don't have to provide it. You can even say you only want to send it from the client (request) `:> Client("Accept", "*")` or server (response) `:> Server("Accept", "*")`. I used that to enable CORS.

Would that be helpful for your problem?

**Comment by pheymann** [comment]
Almost forgot about it. In 0.1.0 you are also able to use `String`s to define singletons for headers, queries and so on. Therefore, you are able to use dashes.

**Comment by wookievx** [comment]
I might have used a wrong word, what i personally need is ability to extract all headers starting with the given prefix from request(and provide any number of that headers when calling an API). But this is still a bit of a long-shot goal, and  not necessarily a must. I would really like to know how to use this string syntax, i assume it is not yet provided with 0.1.0-RC5?

**Comment by pheymann** [comment]
Okay, now I get a clearer picture. On the server-side, it should like something like this:

```Scala
val Api = := :> "header" :> Family("expected-header-prefix") :> Get[Json, A]

derive(Api).from(headers: Set[String] => ???)
```

And on the client-side you would do:

```Scala
val get = derive(Api)

get(Set(???))
```

Or do you mean something different?

The project state in 0.1.0-release isn't released yet. I will publish it at the end of the week I hope. Till then you can check out the branch and work with it locally.

**Comment by pheymann** [comment]
#30

**Comment by pheymann** [comment]
Btw. 0.1.0 is released and includes the matching (family) headers.

**Comment by wookievx** [comment]
For me the current state is satisfactory, so i think this issue can be closed

**Comment by pheymann** [comment]
👍
