### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by wookievx** [pheymann/typedapi#36]
# Motivation
At least for now there is no way of providing your own methods of handling errors, so any error in your service end up being reported as internal server error to the client.  This can be addressed in a project by reimplementing integration with your http-framework of choice. But i think that providing facility to enable custom error handling is quite important. There are certain kinds of failures that are not internal server errors, or implementation issues like resource with given id missing, that should return proper status code and error information to the caller.
# Proposal
Signature of  `Get[MT <: MediaType, A]` and other methods respectively could be changed to something like `Get[MT <: MediaType, E, A]`. Then specific http-framework integrations would have to care about exposing facility to handle errors of type E in a specific way.

**Comment by pheymann** [comment]
To be honest, I haven't put too much thought into this problem before and just went with the successful case (no errors what so ever) 😄 . I think it is time to add error handling (or result status handling at all).

I would again make it more abstract and not dependent on the specific library. My proposal is to change the return type to something like `F[Either[HttpError, A]]` which is used like this:

```Scala
case class HttpError(status: Int, msg: String)

def error(status: Int, msg: String) = Left(HttpError(status, msg))
def error404(msg: String) = error(404, msg)

def success[A](a: A) = Right(a)

val Api = := :> "user" :> Segment[Int]("id") :> Get[Json, User]

derive[IO](Api).from { id =>
  val user: IO[User] = // try to find the user

  user
    .map(success)
    .handleErrorWith {
      case UserNotFound => error404(s"couldn't find user with id $id")
    }
}
```

For the successful case you probably also want to set a specific status code. Right now I am thinking of an extended return-type even further to something like  `F[Either[HttpError, Int -> A]]`:

```Scala
def successWith[A](status: Int)(a: A): F[Either[HttpError, Int -> A]] = Right(status -> a)

derive[IO](Api).from { id =>
  val user: IO[User] = // try to find the user

  user
    .map(successWith(Ok))
    .handleErrorWith {
      case UserNotFound => error404(s"couldn't find user with id $id")
    }
}
```

**Comment by pheymann** [comment]
see #37

**Comment by pheymann** [comment]
0.2.0-RC2 including this change is on its way to Maven.
